services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    container_name: redis_container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  
    container_name: mongo_container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"  
    container_name: cassandra_container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  
      - "7687:7687"  
    container_name: neo4j_container
    environment:
      - NEO4J_AUTH=neo4j/superadmin  
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "superadmin", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    container_name: couchdb_container
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/couchdb_data:/opt/couchdb/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5984/_up" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

